Repository AdobeDocs/uxp-photoshop, pull requests merged in 2020-10, with the labels that each got.

#5 Update config and dep
  gatsby-config.js
  package.json
  yarn.lock
Labels: deploy, deploy:dev

#7 force react/gatsby version for now
  package.json
  yarn.lock
Labels: deploy:dev

#9 Update lock file
  .github/dependabot.yml
  gatsby-config.js
  package-lock.json
  package.json
Labels: deploy, deploy:dev

#12 Design content from Daniela
  design.js
  gatsby-config.js
  src/pages/design/index.md
  src/pages/design/ux-images/Alert-Information-example-2.png
  src/pages/design/ux-images/Alert-Recommendations.png
  src/pages/design/ux-images/Alert-Requirements.png
  src/pages/design/ux-images/Branding-1.png
  src/pages/design/ux-images/Branding-2.png
  src/pages/design/ux-images/Branding-3.png
  src/pages/design/ux-images/Branding-4.png
  src/pages/design/ux-images/Error-alert-example.png
  src/pages/design/ux-images/Messaging-1.png
  src/pages/design/ux-images/Messaging-example.png
  src/pages/design/ux-images/Onboarding-BP.png
  src/pages/design/ux-images/Permission-dialog-example.png
  src/pages/design/ux-images/Plugin-output.png
  src/pages/design/ux-images/darkThemes.png
  src/pages/design/ux-images/lightThemes.png
  src/pages/design/ux-images/panel-messaging-example.png
  src/pages/design/ux-images/paneldark.png
  src/pages/design/ux-images/paneldarkest.png
  src/pages/design/ux-images/panelight.png
  src/pages/design/ux-images/panellightest.png
  src/pages/design/ux-images/photoshoppanelspecs.png
  src/pages/design/ux-images/plugindialogspecs.png
  src/pages/design/ux-images/pluginsinphotoshop.png
  src/pages/design/ux-images/progress-bar-example.png
  src/pages/design/ux-images/pscontextualtoolsDo.png
  src/pages/design/ux-images/pscontextualtoolsDont.png
  src/pages/design/ux-images/psicondosdonts.png
  src/pages/design/ux-images/psiconexample.png
  src/pages/design/ux-images/psiconguidelines.png
  src/pages/design/ux-images/psiconspecs.png
  src/pages/design/ux-images/pslargewidtdo.png
  src/pages/design/ux-images/pslargewidthdont.png
  src/pages/design/ux-images/psplaceobjectdo.png
  src/pages/design/ux-images/psplaceobjectdont.png
  src/pages/design/ux-images/pspluginlaunchpad.png
  src/pages/design/ux-images/success-Requirements.png
  src/pages/design/ux-patterns/branding.md
  src/pages/design/ux-patterns/designingforPS.md
  src/pages/design/ux-patterns/index.md
  src/pages/design/ux-patterns/messaging.md
  src/pages/design/ux-patterns/onboarding.md
Labels: deploy:dev

#13 Update package.json
  package.json
Labels: deploy:dev

#14 Chuck v5
  gatsby-config.js
  src/pages/code_samples/javascript_samples/index.md
  src/pages/distribution/distribution-options/index.md
  src/pages/distribution/index.md
  src/pages/distribution/marketing/index.md
  src/pages/distribution/packaging-your-plugin/index.md
  src/pages/distribution/publishing/index.md
  src/pages/distribution/submission-checklist/index.md
  src/pages/guides/index.md
  src/pages/guides/ps_basics/batchplay_intro/index.md
  src/pages/guides/uxp-developer-tool/index.md
  src/pages/guides/uxp_for_you/uxp_for_newbies/index.md
  src/pages/guides/uxp_guide/flyout-menus.md
  src/pages/guides/uxp_guide/index.md
  src/pages/guides/uxp_guide/localization-and-platforms.md
  src/pages/guides/uxp_guide/manifest-sample.md
  src/pages/guides/uxp_guide/unsupported/index.md
  src/pages/guides/uxp_guide/uxp-manifest.md
  src/pages/guides/uxp_guide/uxp-misc/file-access/index.md
  src/pages/guides/uxp_guide/uxp-misc/flyout-menus/index.md
  src/pages/guides/uxp_guide/uxp-misc/index.md
  src/pages/guides/uxp_guide/uxp-misc/localization-and-platforms/index.md
  src/pages/guides/uxp_guide/uxp-misc/manifest-v4/index.md
  src/pages/guides/uxp_guide/uxp-misc/network-io/index.md
  src/pages/guides/uxp_guide/uxp-misc/plugin-icons/index.md
  src/pages/guides/uxp_guide/uxp-misc/spectrum-css/index.md
  src/pages/guides/uxp_guide/uxp-toolchain/index.md
  src/pages/index.md
  src/pages/support/FAQ/index.md
  src/pages/support/community/index.md
  src/pages/support/contribute/index.md
  src/pages/support/experience_cloud.png
  src/pages/support/index.md
  src/pages/support/stack-overflow.png
Labels: deploy, deploy:dev

#15 Design updates from Daniela
  design.js
  src/pages/design/index.md
  src/pages/design/ux-patterns/Designingforphotoshop.md
  src/pages/design/ux-patterns/branding.md
  src/pages/design/ux-patterns/index.md
  src/pages/design/ux-patterns/messaging.md
Labels: deploy, deploy:dev

#17 Update package.json
  package.json
Labels: deploy, deploy:dev

#19 Update package.json
  package.json
Labels: deploy, deploy:dev

#21 Update package.json
  package.json
Labels: deploy, deploy:dev

#23 Update package.json
  package.json
Labels: deploy, deploy:dev

#26 Update package.json
  package.json
Labels: deploy, deploy:dev

#28 Update package.json
  package.json
Labels: deploy, deploy:dev

#32 Delete package-lock.json
  package-lock.json
Labels: deploy, deploy:dev

#35 Push stage & prod again
  package.json
Labels: deploy, deploy:dev

#37 Update package.json
  package.json
Labels: deploy, deploy:dev

#39 Update package.json
  package.json
Labels: deploy, deploy:dev

#40 Update package.json
  package.json
Labels: deploy, deploy:dev

#42 Update package.json
  package.json
Labels: deploy, deploy:dev

#44 Update package.json
  package.json
Labels: deploy, deploy:dev

#57 Update package.json
  package.json
Labels: deploy, deploy:dev

#59 Update package.json
  package.json
Labels: deploy, deploy:dev

#61 Update package.json
  package.json
Labels: deploy, deploy:dev

#64 Update package.json
  package.json
Labels: deploy, deploy:dev

#67 Last push around keynote
  package.json
Labels: deploy, deploy:dev

#70 Update package.json
  package.json
Labels: deploy, deploy:dev

#72 Fix GH 404 links
  package.json
  src/@adobe/gatsby-theme-parliament/components/Contributors/index.js
  src/@adobe/gatsby-theme-parliament/components/GitHubActions/index.js
Labels: deploy, deploy:dev

#76 Fix CLI mention & yarn link (#75 from @chuckweger)
  package.json
Labels: deploy, deploy:dev

#81 Fix from @dcaiced0 for design 404s
  package.json
Labels: deploy, deploy:dev

#84 Update dependency
  .github/workflows/pr-approved.yml
  package-lock.json
  package.json
  reference-css.js
  reference-html.js
  reference-js.js
  reference-spectrum.js
  src/@adobe/gatsby-theme-parliament/components/Contributors/index.js
  src/@adobe/gatsby-theme-parliament/components/GitHubActions/index.js
Labels: dependencies, deploy, deploy:dev
