Repository AdobeDocs/uxp-photoshop, pull requests merged in 2020-11, with the labels that each got.

#108 Update package.json
  package.json
Labels: deploy:dev

#109 Deploy to production
  package.json
Labels: deploy

#103 Added new error message. Addresses #73.
  src/pages/distribution/submission-checklist/index.md
Labels: to-deploy

#118 Update dependencies
  README.md
  gatsby-config.js
  package-lock.json
  package.json
Labels: deploy

#113 Fix 404
  src/pages/design/index.md
Labels: 404, to-deploy

#126 Deploy to stage
  package.json
Labels: deploy:dev

#129 Deploy to stage (again)
  package.json
Labels: deploy:dev

#132 Deploy to production
  package.json
Labels: deploy
